### ISSUE TITLE
How did you calculate these values for each emotion ? Like for each feature how did you assign the value did you calculate it or is it random ? 

### ISSUE THREAD

**Issue by omkar806** [ShreyashThengne/Music-Recommendation-System#1]
filt_col = ['acousticness', 'danceability', 'energy', 'loudness', 'tempo', 'valence']

# values for filtering (Emotion specific)
happy_low = [0, 0.57, 0.4, -10.4, 75,0.25]
sad_low = [0.2, 0.3, 0.25, -11, 70, 0]
chill_low = [0, 0.35, 0.25, -12.7, 80, 0.2]
angry_low = [0, 0.46, 0.56, -11, 90, 0.2]

happy_high = [0.75, 0.86, 1, -3, 170, 1]
sad_high = [0.9, 0.7, 0.8, -4, 160, 0.7]
chill_high = [0.85, 0.8, 0.8, -4, 165, 0.9]
angry_high = [0.6, 0.85, 1, -4, 170, 0.75]

happy_avg = [0.715, 0.7, 0.375, -6.7, 0.625, 123]
sad_avg = [0.5, 0.525, 0.55, -7.5, 0.3, 115]
chill_avg = [0.575, 0.525, 0.425, -8.35, 0.55, 122.5]
angry_avg = [0.655, 0.78, 0.3, -7.5, 0.475, 130]

**Comment by ShreyashThengne** [comment]
I had created visualization in excel to understand the trend in those features with respect to each emotion. Actually, I was not aware of machine learning when I was working on this project.

**By the way, you are referring to an older version**. Check out **app.py** file for updated code. I no longer use such metrics for filtering. Instead, when the song data is extracted/updated using extracting_data.ipynb (which you can do by a single complete run of that notebook and inputting a playlist link to it), emotion of the song is identified by feeding the features to a trained neural network model. I had trained the model using the data I extracted from multiple spotify's emotion-specific playlists. I think I have just pushed the _model.h5_ file and not the file I used to train the model. The emotion is entered in the final_data.csv along with other metadata and features. The emotion in that file is directly used to get the songs specific to the detected facial emotion and then make content-based recommendation. Identifying the emotion of the songs, present in the data, in advance saves time and thus aids the response speed of the app.

I hope this helps! Feel free to ask anything.

**Comment by omkar806** [comment]
I was wondering for training the model had you annotated each of the songs data by yourself ? or which approach you had used for classifying the song into an emotion like which values of the features corresponds to which emotions ?

**Comment by omkar806** [comment]
Also if you can add the code for this song classification ?

**Comment by ShreyashThengne** [comment]
I just checked. I think I no longer have the code to that classifier. Although I can explain the process.
See, spotify has playlist specific to emotion, both their own as well as user curated. So, I extracted data from such playlists. Lets say I need songs related to happy emotion, then I would select a certain number of playlists related to this emotion and extract their data and label those with happy emotion. After extracting the data for each emotion, had performed the standard procedures of training any classifier.

**Comment by omkar806** [comment]
Hey so standard procedure for training a classifier is to apply some logistic regression or clustering algos to get some standard values for each feature like dancebility n all right .
which algo you had used or which should work best in this case ?

**Comment by omkar806** [comment]
Also in your blog you have used similaity metric that is cosine similarity , I was wondering like one embedding would be of the emotion that would be generated and and for the songs embeddings were generated from which content because that approach seems to be more good as similarity metric is a good way to classify . As it relies on semantic meaning .
I really want help on this .

**Comment by ShreyashThengne** [comment]
Just forget about that standard values part, as that method would restrict the model output to linear border in space, leading to miss-classifications. I had used a neural network to train on the features data for emotion classification, alternatively you could go for other algo as well like boosted decision trees.

Also, about the separate embedding for emotion, this could work kinda and we will be able to get a confidence score as well. In old code, I had used this method, so I know it is not that effective. I would suggest you go for ml model.

**BLOG IS OUTDATED 😅!**

**Comment by omkar806** [comment]
Hi , I have extracted data from Spotify and even trained a CNN using conv1d for it but my accuracy after testing on test data set is reaching max till 60 percent.
I will shortly share the code and even the dataset.
I have taken 1100 songs for the 5 emotions with all the features available in Spotify api response.
Is there any way I can increase the testing accuracy at least till 70 percent which is decent ? It will be very helpful if you can help me on this . Thankyou in advance.

**Comment by omkar806** [comment]
If I can get a basic idea about dataset distribution and about neural network architecture , I will be good to go.

**Comment by ShreyashThengne** [comment]
I think the model will most probably get confused between 'chill' and 'happy'. Also, there's scarcity of angry songs, so, it may be just okayish. It would be difficult to get better accuracy as emotion is a subjective matter and not all songs have 1 single emotion with them. Remember the playlists were also created by humans (most probably), so data is for sure impure/biased. So, the accuracy you are getting is not really the exact.

**But still if you want to improve accuracy, this might help you.** You can associate the artists with emotions. You can get the data from their profile, considering top # songs, like that. Usually, some artists tend to stick with similar tones/emotion. This may not improve drastically, but is sure to aid a little.

Also, about the arch, I had used fully connected nn. Since the data is not sequential, fully connected is a good choice. I am not sure whether using 1d cnn in this scenario is good or bad, as it is usually good for sequential data.
